export const documents = [
  // === Step 1 ===
  {
    id: 'step-1-powerless',
    title: 'Step 1 Powerless',
    path: '/docs/step-1/step-1-powerless.pdf',
    type: 'pdf',
    steps: [1],
    category: 'Step Work',
    description: 'Powerlessness worksheet for Step 1',
  },
  {
    id: 'step-1-unmanageable',
    title: 'Step 1 Unmanageable',
    path: '/docs/step-1/step-1-unmanageable.docx',
    type: 'docx',
    steps: [1],
    category: 'Step Work',
    description: 'Unmanageability worksheet for Step 1',
  },
  {
    id: 'step-1-part-2',
    title: 'Step 1 Part 2',
    path: '/docs/step-1/step1part2.pdf',
    type: 'pdf',
    steps: [1],
    category: 'Step Work',
    description: 'Additional Step 1 worksheet',
  },

  // === Step 4 Workshop ===
  {
    id: 'glossary',
    title: 'Glossary',
    path: '/docs/step-4-workshop/1-glossary-2.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Glossary of terms for the 4th Step workshop',
  },
  {
    id: 'areas-to-look-for-resentments',
    title: 'Areas to Look for Resentments',
    path: '/docs/step-4-workshop/1-areas-to-look-for-resentments.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Guide for identifying resentments in your inventory',
  },
  {
    id: 'atw-sheets-combined',
    title: 'ATW Sheets Combined',
    path: '/docs/step-4-workshop/1-atw-sheets-combined-9-8-19.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Combined inventory worksheets',
  },
  {
    id: 'resentments-cover-sheet',
    title: 'Resentments Cover Sheet',
    path: '/docs/step-4-workshop/1-resentments-cover-sheet.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Cover sheet for resentments section',
  },
  {
    id: 'resentments-sheet-2',
    title: 'Resentments Sheet 2',
    path: '/docs/step-4-workshop/1-resentmentssheet2.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Additional resentments worksheet',
  },
  {
    id: 'areas-to-look-for-fears',
    title: 'Areas to Look for Fears',
    path: '/docs/step-4-workshop/3-areas-to-look-for-fears.docx',
    type: 'docx',
    steps: [4],
    category: 'Workshop',
    description: 'Guide for identifying fears in your inventory',
  },
  {
    id: 'fears-cover-sheet',
    title: 'Fears Cover Sheet',
    path: '/docs/step-4-workshop/3-fears-cover-sheet-10-1-17.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Cover sheet for fears section',
  },
  {
    id: 'fears-sheet-2',
    title: 'Fears Sheet 2',
    path: '/docs/step-4-workshop/3-fearssheet-2-10-1-17.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Additional fears worksheet',
  },
  {
    id: 'areas-sex-and-other-harms',
    title: 'Areas to Look for Sex and Other Harms',
    path: '/docs/step-4-workshop/4-areas-to-look-for-sex-and-other-harms-1.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Guide for identifying harms in your inventory',
  },
  {
    id: 'harms-cover-sheet',
    title: 'Harms Cover Sheet',
    path: '/docs/step-4-workshop/4-harms-cover-sheet-10-1-17.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Cover sheet for harms section',
  },
  {
    id: 'harms-sheet-2',
    title: 'Harms Sheet 2',
    path: '/docs/step-4-workshop/4-harms-sheet-2-10-12-21.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Additional harms worksheet',
  },
  {
    id: '5th-step-questions',
    title: '5th Step Questions',
    path: '/docs/step-4-workshop/5-5th-step-questions.pdf',
    type: 'pdf',
    steps: [4, 5],
    category: 'Workshop',
    description: 'Questions to prepare for your 5th Step',
  },
  {
    id: '5th-step-answers',
    title: 'Answers to 5th Step Questions',
    path: '/docs/step-4-workshop/5-answers-to-5th-step-questions.pdf',
    type: 'pdf',
    steps: [4, 5],
    category: 'Workshop',
    description: 'Answer guide for 5th Step questions',
  },
  {
    id: 'guidelines-summaries-instructions',
    title: 'Guidelines & Summaries Instructions',
    path: '/docs/step-4-workshop/5-guidelines-summaries-instructions.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Instructions for writing inventory summaries',
  },
  {
    id: '8th-step-list',
    title: '8th Step List',
    path: '/docs/step-4-workshop/6-8th-step-list.pdf',
    type: 'pdf',
    steps: [4, 8],
    category: 'Workshop',
    description: '8th Step amends list worksheet',
  },
  {
    id: 'daily-inventory',
    title: 'Daily Inventory',
    path: '/docs/step-4-workshop/6-daily-inventory.pdf',
    type: 'pdf',
    steps: [4, 10],
    category: 'Workshop',
    description: 'Daily inventory worksheet',
  },
  {
    id: 'agenda-week-1',
    title: 'Agenda Week 1',
    path: '/docs/step-4-workshop/agenda-week-1-rev-9-25.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Week 1 workshop agenda',
  },
  {
    id: 'agenda-week-2',
    title: 'Agenda Week 2',
    path: '/docs/step-4-workshop/agenda-week-2-rev-4-25.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Week 2 workshop agenda',
  },
  {
    id: 'agenda-week-3',
    title: 'Agenda Week 3',
    path: '/docs/step-4-workshop/agenda-week-3-rev-4-25.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Week 3 workshop agenda',
  },
  {
    id: 'agenda-week-4',
    title: 'Agenda Week 4',
    path: '/docs/step-4-workshop/agenda-week-4-rev-9-25.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Week 4 workshop agenda',
  },
  {
    id: 'agenda-week-5',
    title: 'Agenda Week 5',
    path: '/docs/step-4-workshop/agenda-week-5-rev-9-25.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Week 5 workshop agenda',
  },
  {
    id: 'agenda-week-6',
    title: 'Agenda Week 6',
    path: '/docs/step-4-workshop/agenda-week-6-rev-4-25.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Week 6 workshop agenda',
  },
  {
    id: 'week-1-readings',
    title: 'Week 1 Readings for Participants',
    path: '/docs/step-4-workshop/week-one-readings-for-participants.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Readings',
    description: 'Reading materials for workshop week 1',
  },
  {
    id: 'week-2-readings',
    title: 'Week 2 Readings for Participants',
    path: '/docs/step-4-workshop/week-2-readings-for-participants.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Readings',
    description: 'Reading materials for workshop week 2',
  },
  {
    id: 'week-3-readings',
    title: 'Week 3 Readings for Participants',
    path: '/docs/step-4-workshop/week-3-readings-for-participants.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Readings',
    description: 'Reading materials for workshop week 3',
  },
  {
    id: 'week-4-readings',
    title: 'Week 4 Readings for Participants',
    path: '/docs/step-4-workshop/week-4-readings-for-participants.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Readings',
    description: 'Reading materials for workshop week 4',
  },
  {
    id: 'week-6-readings',
    title: 'Week 6 Readings for Participants',
    path: '/docs/step-4-workshop/week-6-readings-for-participants.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Readings',
    description: 'Reading materials for workshop week 6',
  },
  {
    id: 'receiver-suggestions',
    title: 'Receiver Suggestions',
    path: '/docs/step-4-workshop/receiver-suggestions.pdf',
    type: 'pdf',
    steps: [4, 5],
    category: 'Workshop',
    description: 'Suggestions for the person receiving a 5th Step',
  },
  {
    id: 'suggested-preparation-5th-step',
    title: 'Suggested Preparation for 5th Step',
    path: '/docs/step-4-workshop/suggested-preparation-for-5th-step.pdf',
    type: 'pdf',
    steps: [4, 5],
    category: 'Workshop',
    description: 'How to prepare for sharing your 5th Step',
  },
  {
    id: 'scott-selfish-resentment-summary',
    title: 'Scott: Selfish Resentment Summary',
    path: '/docs/step-4-workshop/scott-selfishresentment-summary.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Examples',
    description: 'Example summary — selfish resentment (Scott)',
  },
  {
    id: 'doris-selfish-resentment-summary',
    title: 'Doris: Selfish Resentment Summary',
    path: '/docs/step-4-workshop/doris-selfishresentment-summary.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Examples',
    description: 'Example summary — selfish resentment (Doris)',
  },
  {
    id: 'nathan-inconsiderate-resentment-summary',
    title: 'Nathan: Inconsiderate Resentment Summary',
    path: '/docs/step-4-workshop/nathan-inconsiderateresentment-summary.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Examples',
    description: 'Example summary — inconsiderate resentment (Nathan)',
  },
  {
    id: 'doris-inconsiderate-fear-summary',
    title: 'Doris: Inconsiderate Fear Summary',
    path: '/docs/step-4-workshop/doris-inconsideratefear-summary.doc',
    type: 'doc',
    steps: [4],
    category: 'Examples',
    description: 'Example summary — inconsiderate fear (Doris)',
  },
  {
    id: 'fred-inconsiderate-resentment-summary',
    title: 'Fred: Inconsiderate Resentment Summary',
    path: '/docs/step-4-workshop/fred-inconsiderateresentment-summary.doc',
    type: 'doc',
    steps: [4],
    category: 'Examples',
    description: 'Example summary — inconsiderate resentment (Fred)',
  },
  {
    id: 'tammy-dishonest-resentment-summary',
    title: 'Tammy: Dishonest Resentment Summary',
    path: '/docs/step-4-workshop/tammy-dishonestresentmentsummary.docx',
    type: 'docx',
    steps: [4],
    category: 'Examples',
    description: 'Example summary — dishonest resentment (Tammy)',
  },
  {
    id: 'mike-self-seeking-resentment-summary',
    title: 'Mike: Self-Seeking Resentment Summary',
    path: '/docs/step-4-workshop/mike-selfseekingresentment-summary.docx',
    type: 'docx',
    steps: [4],
    category: 'Examples',
    description: 'Example summary — self-seeking resentment (Mike)',
  },

  // === Step 4 Images ===
  {
    id: 'step-4-img-8050',
    title: 'Step 4 Example Page 1',
    path: '/docs/step-4-images/img-8050.jpg',
    type: 'image',
    steps: [4],
    category: 'Examples',
    description: 'Handwritten inventory example page',
  },
  {
    id: 'step-4-img-8051',
    title: 'Step 4 Example Page 2',
    path: '/docs/step-4-images/img-8051.jpg',
    type: 'image',
    steps: [4],
    category: 'Examples',
    description: 'Handwritten inventory example page',
  },
  {
    id: 'step-4-img-8052',
    title: 'Step 4 Example Page 3',
    path: '/docs/step-4-images/img-8052.jpg',
    type: 'image',
    steps: [4],
    category: 'Examples',
    description: 'Handwritten inventory example page',
  },
  {
    id: 'step-4-img-8053',
    title: 'Step 4 Example Page 4',
    path: '/docs/step-4-images/img-8053.jpg',
    type: 'image',
    steps: [4],
    category: 'Examples',
    description: 'Handwritten inventory example page',
  },
  {
    id: 'step-4-img-8054',
    title: 'Step 4 Example Page 5',
    path: '/docs/step-4-images/img-8054.jpg',
    type: 'image',
    steps: [4],
    category: 'Examples',
    description: 'Handwritten inventory example page',
  },
  {
    id: 'step-4-img-8055',
    title: 'Step 4 Example Page 6',
    path: '/docs/step-4-images/img-8055.jpg',
    type: 'image',
    steps: [4],
    category: 'Examples',
    description: 'Handwritten inventory example page',
  },
  {
    id: 'step-4-img-8056',
    title: 'Step 4 Example Page 7',
    path: '/docs/step-4-images/img-8056.jpg',
    type: 'image',
    steps: [4],
    category: 'Examples',
    description: 'Handwritten inventory example page',
  },
  {
    id: 'step-4-img-8058',
    title: 'Step 4 Example Page 8',
    path: '/docs/step-4-images/img-8058.jpg',
    type: 'image',
    steps: [4],
    category: 'Examples',
    description: 'Handwritten inventory example page',
  },
  {
    id: 'step-4-img-8059',
    title: 'Step 4 Example Page 9',
    path: '/docs/step-4-images/img-8059.jpg',
    type: 'image',
    steps: [4],
    category: 'Examples',
    description: 'Handwritten inventory example page',
  },
  {
    id: 'step-4-img-8060',
    title: 'Step 4 Example Page 10',
    path: '/docs/step-4-images/img-8060.jpg',
    type: 'image',
    steps: [4],
    category: 'Examples',
    description: 'Handwritten inventory example page',
  },
  {
    id: 'step-4-img-8061',
    title: 'Step 4 Example Page 11',
    path: '/docs/step-4-images/img-8061.jpg',
    type: 'image',
    steps: [4],
    category: 'Examples',
    description: 'Handwritten inventory example page',
  },
  {
    id: 'step-4-img-8062',
    title: 'Step 4 Example Page 12',
    path: '/docs/step-4-images/img-8062.jpg',
    type: 'image',
    steps: [4],
    category: 'Examples',
    description: 'Handwritten inventory example page',
  },
  {
    id: 'step-4-img-8065',
    title: 'Step 4 Example Page 13',
    path: '/docs/step-4-images/img-8065.jpg',
    type: 'image',
    steps: [4],
    category: 'Examples',
    description: 'Handwritten inventory example page',
  },
  {
    id: 'step-4-resentments-image',
    title: 'Resentments Example',
    path: '/docs/step-4-images/resentments.jpg',
    type: 'image',
    steps: [4],
    category: 'Examples',
    description: 'Visual example of resentments inventory',
  },

  // === Step 9 ===
  {
    id: 'amends-outline',
    title: 'Amends Outline',
    path: '/docs/step-9/amends-outline.docx',
    type: 'docx',
    steps: [9],
    category: 'Step Work',
    description: 'Template for outlining your amends',
  },
  {
    id: 'amends-to-my-brother',
    title: 'Amends to My Brother',
    path: '/docs/step-9/amends-to-my-brother.docx',
    type: 'docx',
    steps: [9],
    category: 'Examples',
    description: 'Example amends letter to a family member',
  },

  // === Step 10 ===
  {
    id: 'step-10-worksheet',
    title: 'Step 10 Worksheet',
    path: '/docs/step-10/step-10.docx',
    type: 'docx',
    steps: [10],
    category: 'Step Work',
    description: 'Daily inventory worksheet for Step 10',
  },
  {
    id: 'step-10-image',
    title: 'Step 10 Reference',
    path: '/docs/step-10/48493.jpg',
    type: 'image',
    steps: [10],
    category: 'Examples',
    description: 'Step 10 reference image',
  },

  // === Paul's Workshop ===
  {
    id: 'basic-instincts',
    title: 'Basic Instincts',
    path: '/docs/pauls-workshop/basic-instincts.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Overview of basic human instincts in inventory work',
  },
  {
    id: 'pauls-trauma-template',
    title: "Paul's Trauma Template",
    path: '/docs/pauls-workshop/paul-s-trauma-template.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Template for processing trauma in step work',
  },
  {
    id: 'step-four-bb-worksheets',
    title: 'Step Four Big Book Worksheets',
    path: '/docs/pauls-workshop/step-four-bb-worksheets.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Big Book-based worksheets for Step 4',
  },
  {
    id: 'keystonefoundation',
    title: 'Keystone Foundation',
    path: '/docs/pauls-workshop/keystonefoundation.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Readings',
    description: 'Keystone Foundation recovery materials',
  },
  {
    id: 'online-session-handouts',
    title: 'Online Session Handouts',
    path: '/docs/pauls-workshop/online-session-handouts.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Workshop',
    description: 'Handouts for online step workshop sessions',
  },
  {
    id: 'deadly-needs',
    title: 'Deadly Needs',
    path: '/docs/pauls-workshop/deadly-needs.docx',
    type: 'docx',
    steps: [4],
    category: 'Readings',
    description: 'Reading on destructive emotional needs',
  },
  {
    id: 'attachments-form-beliefs',
    title: 'Attachments Form Beliefs',
    path: '/docs/pauls-workshop/attachments-form-beliefs.pdf',
    type: 'pdf',
    steps: [4],
    category: 'Readings',
    description: 'How attachments form our belief systems',
  },
  {
    id: 'suggested-reading-list',
    title: 'Suggested Reading List',
    path: '/docs/pauls-workshop/suggested-reading-list.docx',
    type: 'docx',
    steps: [4],
    category: 'Readings',
    description: 'Recommended books and readings for step work',
  },

  // === Back to Basics ===
  {
    id: 'back-to-basics-edits',
    title: 'Back to Basics (Edited)',
    path: '/docs/back-to-basics/back-2-basics-edits-10.12.25.docx',
    type: 'docx',
    steps: [],
    category: 'General',
    description: 'Edited version of Back to Basics sponsorship guide',
  },
  {
    id: 'original-back-to-basics',
    title: 'Original Back to Basics of Sponsorship',
    path: '/docs/back-to-basics/original-back-to-basics-of-sponsorship.pdf',
    type: 'pdf',
    steps: [],
    category: 'General',
    description: 'Original Back to Basics of Sponsorship guide',
  },
  {
    id: 'four-spiritual-activities',
    title: 'Four Spiritual Activities Reading Pages',
    path: '/docs/back-to-basics/four-spiritual-activities-reading-pages-handout.docx',
    type: 'docx',
    steps: [],
    category: 'Readings',
    description: 'Handout on the four spiritual activities',
  },
  {
    id: 'notes-from-kenny',
    title: 'Notes About Back to Basics from Kenny',
    path: '/docs/back-to-basics/notes-and-thoughts-about-back-to-basics-from-kenny.docx',
    type: 'docx',
    steps: [],
    category: 'General',
    description: "Kenny's notes and thoughts on Back to Basics",
  },
  {
    id: 'back-to-basics-master',
    title: 'Back to Basics Master',
    path: '/docs/back-to-basics/master.docx',
    type: 'docx',
    steps: [],
    category: 'General',
    description: 'Master document for Back to Basics',
  },

  // === General ===
  {
    id: 'sponsoring',
    title: 'Sponsoring Guide',
    path: '/docs/general/sponsoring.docx',
    type: 'docx',
    steps: [],
    category: 'General',
    description: 'General guide to sponsoring others in recovery',
  },
];

export function getDocumentsForStep(stepNumber) {
  return documents.filter((doc) => doc.steps.includes(stepNumber));
}

export function getGeneralDocuments() {
  return documents.filter((doc) => doc.steps.length === 0);
}

export function getDocumentsByCategory(category) {
  return documents.filter((doc) => doc.category === category);
}

export function isPreviewable(doc) {
  return doc.type === 'pdf' || doc.type === 'image';
}

export const categories = ['Step Work', 'Workshop', 'Examples', 'Readings', 'General'];
