export const stepsResources = [
{
    step: 1,
    title: "Step 1: We admitted we were powerless over alcohol—that our lives had become unmanageable.",
    description: [
      "POWERLESSNESS over alcohol means the inability to consistently control alcohol use despite consequences.",
      "UNMANAGEABILITY refers to the chaos and disorder in our lives resulting from alcoholism, whether actively drinking or not.",
    ],
    instructions: "Write examples of how each of the following have shown up in your life. Include your emotional response to each example, such as pain, anger, shame, guilt, and fear.",
    prompts: [
      "PROGRESSION: This may mean using alcohol more often or for longer periods of time, increasing or losing tolerance, for it",
      "LOSS OF CONTROL: This may mean trying to cut down on your use, not using and then using as much or more often than before, not drinking for days, weeks or months",
      "DESTRUCTIVE BEHAVIOR: Examples may include physical or verbal abuse, destruction of property, suicide attempts, self-destructive behaviors",
      "PREOCCUPATION: May mean looking forward to using alcohol, setting up situations to use, having a good supply on hand at all times",
      "PROTECTIONS: These behaviors may include hiding bottles, sneaking alcohol, using breath sprays to cover up, switching liqour stores",
      "JUSTIFYING ALCOHOL USE: Examples may include blaming people or situations for my alcoholism, making excuses, and/or rationalizing use",
      "FINANCIAL PROBLEMS: Examples may include spending money on alcohol instead of food or rent. Having no savings, retirement plan, insurance, etc. Making poor financial decisions",
      "WORK PROBLEMS: These may include being fired, jumping from job to job, poor work performance, high absenteeism, low motivation for success, disorganized household",
      "PHYSICAL DETERIORATION: Symptoms include loss of physical attractiveness, liver/health problems, nervousness, weight loss/gain, disturbed eating and/or sleeping patterns, continued use of alchohol despite medical advice",
      "SPIRITUAL EMPTINESS: There may be a conflict between your values and your behavior, spiritual longings, secret fear that God is not really there, resentment for a God that allows injustice",
      "FAMILY AND SOCIAL PROBLEMS: These may include communication problems, loss of family, friends, social isolation, separation or divorce",
      "EMOTIONAL PROBLEMS: These may refer to extreme anxiety, inability to express feelings unless drinking, difficulty in expressing anger appropriately, depressions, loneliness, moodiness",
      "SEXUAL PROBLEMS: May include impotence, being non-orgasmic, indifference towards sex, inappropriate sexual behavior, sexual identity conflicts",
      "LIFE GOAL PROBLEMS: These may refer to eucation issues, frequent goal changes, frequent geographic moves, frequent relationships, marriages, divorces"
    ],
    // You can add more arrays later, e.g., quotes: [], bigBookPages: [], etc.
  },
  { step: 2, 
    title: "Step 2: Came to believe that a Power grater than ourselves could restore us to sanity",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 3,
    title: "Step 3: Made a decision to turn our will and our lives over to the care of God as we understood him.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 4,
    title: "Step: 4: Made a searhing and fearless moral inventory of ourselves",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 5,
    title: "Step 5: Admitted to God, to ourselves and to another human being the exact nature of our wrongs.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 6,
    title: "Step 6: Were entirely ready to have God remove all these defects of character.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 7,
    title: "Step 7: Humbly asked Him to remove our shortcomings.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 8,
    title: "Step 8: Made a list of all persons we had harmed, and became willing to make amends to them all.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 9,
    title: "Step 9: Made direct amends to such people wherever possible, except when to do so would injure them or others.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 10,
    title: "Step 10: Continued to take personal inventory and when we were wrong promptly admitted it.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 11,
    title: "Step 11: Sought through prayer and meditation to improve our concious contact with God as we understood Him, praying only for knowledge of His will for us and the power to carry that out.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 12,
    title: "Step 12, Having had a spiritual awakening as the result of these steps, we tried to carry this message to alcoholics, and to practice these principles in all our affairs.",
    description: "",
    instructions: "",
    prompts: "",
  }
]
