export const stepsResources = [
{
    step: 1,
    title: "Step 1: We admitted we were powerless over alcohol—that our lives had become unmanageable.",
    instructions: "Write examples of how each of the following have shown up in your life. Include your emotional response to each example, such as pain, anger, shame, guilt, and fear.",

    subsections: {
      powerlessness: {
        label: "Powerlessness",
        description: "Powerlessness over alcohol means the inability to consistently control alcohol use despite consequences.",
        prompts: [
          "PROGRESSION: This may mean using alcohol more often or for longer periods of time, increasing or losing tolerance",
          "LOSS OF CONTROL: Trying to cut down on use, not using and then using as much or more, long periods of abstinence followed by relapse",
          "DESTRUCTIVE BEHAVIOR: Physical or verbal abuse, destruction of property, suicide attempts, self-destructive behaviors",
          "PREOCCUPATION: Looking forward to using, setting up situations to use, keeping a constant supply",
          "PROTECTIONS: Hiding bottles, sneaking alcohol, using breath sprays, switching liquor stores",
          "JUSTIFYING ALCOHOL USE: Blaming others or situations, making excuses, rationalizing continued drinking",
          "PHYSICAL DETERIORATION: Continued use despite health problems, liver issues, weight changes, sleep/eating disturbances",
          "SEXUAL PROBLEMS: Impotence, indifference, inappropriate behavior, identity conflicts"
          // Add the exact 8 you want here
        ]
      },
      unmanageability: {
        label: "Unmanageability",
        description: "Unmanageability refers to the chaos and disorder in our lives resulting from alcoholism, whether actively drinking or not.",
        prompts: [
          "FINANCIAL PROBLEMS: Spending money on alcohol over essentials, no savings, poor financial decisions",
          "WORK PROBLEMS: Job loss, frequent changes, poor performance, absenteeism, disorganized home",
          "SPIRITUAL EMPTINESS: Conflict between values and behavior, resentment toward God, feeling spiritually disconnected",
          "FAMILY AND SOCIAL PROBLEMS: Communication breakdown, loss of relationships, isolation, separation/divorce",
          "EMOTIONAL PROBLEMS: Extreme anxiety, mood swings, depression, loneliness, difficulty expressing feelings",
          "LIFE GOAL PROBLEMS: Education issues, frequent moves, relationship instability, inability to follow through on goals"
          // Add the exact 6 here
        ]
      }
    }
  },
  { step: 2, 
    title: "Step 2: Came to believe that a Power grater than ourselves could restore us to sanity",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 3,
    title: "Step 3: Made a decision to turn our will and our lives over to the care of God as we understood him.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 4,
    title: "Step: 4: Made a searhing and fearless moral inventory of ourselves",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 5,
    title: "Step 5: Admitted to God, to ourselves and to another human being the exact nature of our wrongs.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 6,
    title: "Step 6: Were entirely ready to have God remove all these defects of character.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 7,
    title: "Step 7: Humbly asked Him to remove our shortcomings.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 8,
    title: "Step 8: Made a list of all persons we had harmed, and became willing to make amends to them all.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 9,
    title: "Step 9: Made direct amends to such people wherever possible, except when to do so would injure them or others.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 10,
    title: "Step 10: Continued to take personal inventory and when we were wrong promptly admitted it.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 11,
    title: "Step 11: Sought through prayer and meditation to improve our concious contact with God as we understood Him, praying only for knowledge of His will for us and the power to carry that out.",
    description: "",
    instructions: "",
    prompts: "",
  },
  { step: 12,
    title: "Step 12, Having had a spiritual awakening as the result of these steps, we tried to carry this message to alcoholics, and to practice these principles in all our affairs.",
    description: "",
    instructions: "",
    prompts: "",
  }
]
